### ISSUE TITLE
Fail to create MenuItem when menu name is longer than 56

### ISSUE THREAD

**Issue by Mararsh** [Mararsh/MyBox#1266]
Caused by: java.lang.StringIndexOutOfBoundsException: begin 56, end 57, length 56
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.layoutLabelInArea(LabeledSkinBase.java:590)
	at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.layoutLabelInArea(LabeledSkinBase.java:461)
	at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.layoutChildren(LabeledSkinBase.java:445)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1207)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:579)
	at javafx.graphics/javafx.scene.Scene$2$1.doLayoutPass(Scene.java:441)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1777)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:396)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1114)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1190)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1205)
	at javafx.graphics/javafx.stage.PopupWindow.showImpl(PopupWindow.java:475)
	at javafx.graphics/javafx.stage.PopupWindow.show(PopupWindow.java:420)
	at javafx.controls/javafx.scene.control.ContextMenu.doShow(ContextMenu.java:318)
	at javafx.controls/javafx.scene.control.ContextMenu.show(ContextMenu.java:278)
	at mara.mybox.fxml.LocateTools.locateMouse(LocateTools.java:67)
	at mara.mybox.fxml.RecentVisitMenu.pop(RecentVisitMenu.java:146)
	at mara.mybox.controller.BaseController_Files.popSourceFile(BaseController_Files.java:330)

**Comment by Mararsh** [comment]
This may be an issue of javafx.

Same as https://github.com/Mararsh/MyBox/issues/1222

**Comment by Mararsh** [comment]
As practice, "_" should not be in the text of menu item. Issue solved when replace all "_" as " ".
