### ISSUE TITLE
Endless java.lang.NullPointerException: "com.sun.prism.d3d.D3DTextureResource.getResource()" is null

### ISSUE THREAD

**Issue by Mararsh** [Mararsh/MyBox#1544]
java.lang.NullPointerException: Cannot invoke "com.sun.prism.d3d.D3DTextureData.getContext()" because the return value of "com.sun.prism.d3d.D3DTextureResource.getResource()" is null
	at javafx.graphics@18.0.1/com.sun.prism.d3d.D3DTexture.getContext(D3DTexture.java:85)
	at javafx.graphics@18.0.1/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:210)
	at javafx.graphics@18.0.1/com.sun.prism.d3d.D3DTexture.update(D3DTexture.java:154)
	at javafx.graphics@18.0.1/com.sun.prism.impl.BaseContext.flushMask(BaseContext.java:115)
	at javafx.graphics@18.0.1/com.sun.prism.impl.BaseContext.drawQuads(BaseContext.java:124)
	at javafx.graphics@18.0.1/com.sun.prism.impl.VertexBuffer.flush(VertexBuffer.java:98)
	at javafx.graphics@18.0.1/com.sun.prism.impl.BaseContext.flushVertexBuffer(BaseContext.java:107)
	at javafx.graphics@18.0.1/com.sun.prism.impl.ps.BaseShaderContext.setRenderTarget(BaseShaderContext.java:789)
	at javafx.graphics@18.0.1/com.sun.prism.impl.BaseContext.setRenderTarget(BaseContext.java:149)
	at javafx.graphics@18.0.1/com.sun.prism.impl.ps.BaseShaderContext.checkState(BaseShaderContext.java:679)
	at javafx.graphics@18.0.1/com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(BaseShaderContext.java:612)
	at javafx.graphics@18.0.1/com.sun.prism.impl.ps.BaseShaderContext.validateTextureOp(BaseShaderContext.java:523)
	at javafx.graphics@18.0.1/com.sun.prism.impl.BaseGraphics.drawTexture(BaseGraphics.java:432)
	at javafx.graphics@18.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.drawTexture(BaseShaderGraphics.java:157)
	at javafx.web/com.sun.javafx.webkit.prism.WCPageBackBufferImpl.flush(WCPageBackBufferImpl.java:71)
	at javafx.web/com.sun.webkit.WebPage.paint(WebPage.java:712)
	at javafx.web/com.sun.javafx.sg.prism.web.NGWebView.renderContent(NGWebView.java:95)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2066)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2066)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
	at javafx.graphics@18.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:480)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:321)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Mararsh** [comment]
When load following address with WebView, this error appears endlessly and causes app blocked:

https://wenku.baidu.com/view/5f1c8a0dccc789eb172ded630b1c59eef8c79a15.html
