### ISSUE TITLE
Thread still running after MyBox exit, which can prevent MyBox from starting again

### ISSUE THREAD

**Issue by Mararsh** [Mararsh/MyBox#286]
Recreate the issue: 
1) Input wrong address in Web Broswer of HTML Editor and the web page is failed to be loaded.
2) Then close MyBox
3) Now try to start MyBox.
4) Some thread still be running and MyBox can not be started again.

After testing and checking codes, I found this issue is related to base codes of Javafx: When wrong page loaded in Web Engine, following error popped and this issue will follow

```
java.lang.IllegalStateException: Service must only be used from the FX Application Thread
	at javafx.concurrent.Service.checkThread(Service.java:906)
	at javafx.concurrent.Service.isRunning(Service.java:224)
	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.startLoader(WCImageDecoderImpl.java:144)
	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.getImageFrame(WCImageDecoderImpl.java:329)
	at com.sun.javafx.webkit.prism.WCImageDecoderImpl.getFrame(WCImageDecoderImpl.java:272)
```
Solution: To end JVM finally, run following 2 statements:

```
 Platform.exit();        // Some thread may still be alive after this
 System.exit(0);
```

**Comment by Mararsh** [comment]
Fixed in v5.1
